name: deploy_to_firebase_hosting

on:
  pull_request:
    branches:
      - master

jobs:
  deploy_to_firebase_hosting:

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      
      - name: Install node
        uses: actions/setup-node@master
        with:
          node-version: '12.x'
          
      - run: |
          npm config set "@fortawesome:registry" https://npm.fontawesome.com/
          npm config set '//npm.fontawesome.com/:_authToken' "${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}"
      
      - name: Install dependencies
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

      - name: Build the application
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build
      
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v1.3.0
        with:
          args: deploy --only hosting:timebomb
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
